openapi: 3.0.0
info:
  title: Simple FlaskRESTful API
  description: FlaskRESTful API to maintain notes.
  version: 1.0.0

servers:
  - url: loclalhost:5000
    description: development server

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []

paths:
  /:
    get:
      summary: Welcome Message
      responses:
        "200":
          description: Successfully displays a welcome message
          content:
            application/json:
              schema:
                type: string
                
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /see:
    get:
      summary: see all your notes
      responses:
        "200":
          description: Successfully returns all notes
          content:
            application/json:
              schema:
                type: json 
                items:
                  type: object
                  properties:
                    color_code:
                      type: string
                    message:
                      type: string
                    name:

        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  
  /addnote:
    post:
      description: add a new note
      body:
      content:
        application/json:
          schema: 
            type: object
            properties:
              name:
                type: string
              color:
                type: string
              message:
                type: string

      responses:
        "200":
          description: Successfully added a Note
          content:
            application/json:
              schema:
                type: string

        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /fetchnote:
    post:
      description:  Fetch a specific note
      body:
      content:
        application/json:
          schema: 
            type: object
            properties:
              name:
                type: string

      responses:
        "200":
          description: Successfully fetched a note
          content:
            application/json:
              schema:
                type: object
                properties:
                  color_code:
                    type: string
                  message:
                    type: string
                    name: 
                      type: string

        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              
  /updatecolor:
    patch:
      description:  updates color of note
      body:
      content:
        application/json:
          schema: 
            type: object
            properties:
              name:
                type: string
              color_code: 
                type: string

      responses:
        "200":
          description: Updated color
          content:
            application/json:
              schema:
                type: string

        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  
  /delete/{id}:
    delete:
      description:  Delete note having given id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Deleted entry for {id}
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  